[phases.setup]
nixPkgs = ["php82", "composer"]

[phases.install]
cmds = [
  "cd backend && composer install --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
  "cd backend && php artisan config:cache",
  "cd backend && php artisan route:cache",
  "cd backend && php artisan view:cache"
]

[start]
cmd = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"

