<?php

namespace Database\Seeders;

use App\Models\CashGame;
use Illuminate\Database\Seeder;

class CashGameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cashGames = [
            [
                'name' => 'High Stakes NLHE Table 1',
                'slug' => 'high-stakes-nlhe-table-1',
                'description' => 'Premium high stakes No Limit Hold\'em cash game. For serious players looking for big action and deep stacks.',
                'table_number' => 1,
                'seats_per_table' => 9,
                'max_players' => 9,
                'min_players' => 2,
                'small_blind' => 25.00,
                'big_blind' => 50.00,
                'min_buy_in' => 500.00,
                'max_buy_in' => 5000.00,
                'default_buy_in' => 1000.00,
                'rake_type' => 'percentage',
                'rake_percentage' => 5.00,
                'rake_cap' => 10.00,
                'time_charge_amount' => null,
                'time_charge_interval' => null,
                'game_type' => 'texas_holdem',
                'structure' => 'nlhe',
                'venue_name' => 'Tbilisi Poker Club',
                'address' => '12 Rustaveli Avenue',
                'city' => 'Tbilisi',
                'country' => 'Georgia',
                'postal_code' => '0108',
                'latitude' => 41.7151,
                'longitude' => 44.8271,
                'opens_at' => now()->setTime(12, 0),
                'closes_at' => now()->setTime(4, 0)->addDay(),
                'operating_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
                'allow_reservations' => true,
                'auto_seat_assignment' => true,
                'require_approval' => false,
                'enable_waiting_list' => true,
                'max_waiting_list' => 10,
                'allow_rebuy' => true,
                'allow_side_pots' => true,
                'show_hand_history' => true,
                'status' => 'active',
                'current_players' => 0,
                'total_pot' => 0.00,
                'total_rake' => 0.00,
                'hands_played' => 0,
                'last_hand_at' => null,
                'is_featured' => true,
                'is_published' => true,
                'contact_name' => 'Cash Game Manager',
                'contact_email' => 'cashgames@tbilisipoker.ge',
                'contact_phone' => '+995 555 123 456',
            ],
            [
                'name' => 'Mid Stakes PLO Table 2',
                'slug' => 'mid-stakes-plo-table-2',
                'description' => 'Pot Limit Omaha cash game with medium stakes. Perfect for PLO enthusiasts who want consistent action.',
                'table_number' => 2,
                'seats_per_table' => 8,
                'max_players' => 8,
                'min_players' => 2,
                'small_blind' => 10.00,
                'big_blind' => 20.00,
                'min_buy_in' => 200.00,
                'max_buy_in' => 2000.00,
                'default_buy_in' => 500.00,
                'rake_type' => 'percentage',
                'rake_percentage' => 4.00,
                'rake_cap' => 8.00,
                'time_charge_amount' => 5.00,
                'time_charge_interval' => 30,
                'game_type' => 'plo',
                'structure' => 'pot_limit',
                'venue_name' => 'Tbilisi Poker Club',
                'address' => '12 Rustaveli Avenue',
                'city' => 'Tbilisi',
                'country' => 'Georgia',
                'postal_code' => '0108',
                'latitude' => 41.7151,
                'longitude' => 44.8271,
                'opens_at' => now()->setTime(14, 0),
                'closes_at' => now()->setTime(2, 0)->addDay(),
                'operating_days' => ['tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
                'allow_reservations' => false,
                'auto_seat_assignment' => true,
                'require_approval' => true,
                'enable_waiting_list' => true,
                'max_waiting_list' => 5,
                'allow_rebuy' => true,
                'allow_side_pots' => false,
                'show_hand_history' => false,
                'status' => 'active',
                'current_players' => 0,
                'total_pot' => 0.00,
                'total_rake' => 0.00,
                'hands_played' => 0,
                'last_hand_at' => null,
                'is_featured' => false,
                'is_published' => true,
                'contact_email' => 'cashgames@tbilisipoker.ge',
                'contact_phone' => '+995 555 123 456',
            ],
            // New cash games (only seed these 2)
            [
                'name' => 'Low Stakes NLHE Table 10',
                'slug' => 'low-stakes-nlhe-table-10',
                'description' => 'Beginner-friendly low stakes No Limit Hold\'em table. Perfect for learning and casual play with friendly atmosphere.',
                'table_number' => 10,
                'seats_per_table' => 6,
                'max_players' => 6,
                'min_players' => 2,
                'small_blind' => 1.00,
                'big_blind' => 2.00,
                'min_buy_in' => 20.00,
                'max_buy_in' => 200.00,
                'default_buy_in' => 50.00,
                'rake_type' => 'time_charge',
                'rake_percentage' => null,
                'rake_cap' => null,
                'time_charge_amount' => 3.00,
                'time_charge_interval' => 30,
                'game_type' => 'texas_holdem',
                'structure' => 'nlhe',
                'venue_name' => 'Batumi Casino & Poker Room',
                'address' => '25 Rustaveli Street',
                'city' => 'Batumi',
                'country' => 'Georgia',
                'postal_code' => '6010',
                'latitude' => 41.6168,
                'longitude' => 41.6367,
                'opens_at' => now()->setTime(10, 0),
                'closes_at' => now()->setTime(23, 0),
                'operating_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
                'allow_reservations' => true,
                'auto_seat_assignment' => false,
                'require_approval' => false,
                'enable_waiting_list' => false,
                'max_waiting_list' => null,
                'allow_rebuy' => true,
                'allow_side_pots' => true,
                'show_hand_history' => true,
                'status' => 'active',
                'current_players' => 0,
                'total_pot' => 0.00,
                'total_rake' => 0.00,
                'hands_played' => 0,
                'last_hand_at' => null,
                'is_featured' => true,
                'is_published' => true,
                'contact_name' => 'Batumi Cash Game Host',
                'contact_email' => 'batumi@tbilisipoker.ge',
                'contact_phone' => '+995 555 234 567',
            ],
            [
                'name' => 'Mixed Game Table 11',
                'slug' => 'mixed-game-table-11',
                'description' => 'Dealer\'s Choice mixed game table featuring various poker variants. Rotating games including HORSE, 8-Game, and more!',
                'table_number' => 11,
                'seats_per_table' => 7,
                'max_players' => 7,
                'min_players' => 3,
                'small_blind' => 5.00,
                'big_blind' => 10.00,
                'min_buy_in' => 100.00,
                'max_buy_in' => 1000.00,
                'default_buy_in' => 300.00,
                'rake_type' => 'percentage',
                'rake_percentage' => 3.00,
                'rake_cap' => 5.00,
                'time_charge_amount' => null,
                'time_charge_interval' => null,
                'game_type' => 'mixed_games',
                'structure' => 'mixed',
                'venue_name' => 'Kutaisi Poker House',
                'address' => '8 Agmashenebeli Avenue',
                'city' => 'Kutaisi',
                'country' => 'Georgia',
                'postal_code' => '4600',
                'latitude' => 42.2679,
                'longitude' => 42.7016,
                'opens_at' => now()->setTime(18, 0),
                'closes_at' => now()->setTime(1, 0)->addDay(),
                'operating_days' => ['friday', 'saturday', 'sunday'],
                'allow_reservations' => true,
                'auto_seat_assignment' => true,
                'require_approval' => true,
                'enable_waiting_list' => true,
                'max_waiting_list' => 8,
                'allow_rebuy' => false,
                'allow_side_pots' => true,
                'show_hand_history' => false,
                'status' => 'active',
                'current_players' => 0,
                'total_pot' => 0.00,
                'total_rake' => 0.00,
                'hands_played' => 0,
                'last_hand_at' => null,
                'is_featured' => false,
                'is_published' => true,
                'contact_name' => 'Kutaisi Mixed Game Host',
                'contact_email' => 'kutaisi@tbilisipoker.ge',
                'contact_phone' => '+995 555 345 678',
            ],
        ];

        // Only seed the last 2 new cash games
        $newCashGames = array_slice($cashGames, -2);
        foreach ($newCashGames as $cashGameData) {
            CashGame::updateOrCreate(
                ['table_number' => $cashGameData['table_number']],
                $cashGameData
            );
        }
    }
}

