<?php

namespace Database\Seeders;

use App\Models\Tournament;
use Illuminate\Database\Seeder;

class TournamentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tournaments = [
            [
                'name' => 'Friday Night Poker Championship',
                'slug' => 'friday-night-poker-championship',
                'description' => 'Join us for our weekly Friday night poker tournament! Great atmosphere, competitive play, and exciting prizes await.',
                'start_date' => now()->addDays(7)->setTime(19, 0),
                'end_date' => now()->addDays(8)->setTime(2, 0),
                'registration_start' => now(),
                'registration_end' => now()->addDays(7)->setTime(18, 30),
                'late_registration_minutes' => 60,
                'venue_name' => 'Tbilisi Poker Club',
                'address' => '12 Rustaveli Avenue',
                'city' => 'Tbilisi',
                'country' => 'Georgia',
                'postal_code' => '0108',
                'latitude' => 41.7151,
                'longitude' => 44.8271,
                'tournament_type' => 'freezeout',
                'game_type' => 'texas_holdem',
                'structure' => 'nlhe',
                'total_tables' => 6,
                'seats_per_table' => 9,
                'buy_in' => 100.00,
                'entry_fee' => 10.00,
                'guaranteed_prize' => 1000.00,
                'starting_stack' => 10000,
                'level_duration' => 20,
                'starting_blinds_small' => 25,
                'starting_blinds_big' => 50,
                'rebuys_allowed' => false,
                'addon_allowed' => false,
                'waiting_list_enabled' => true,
                'max_waiting_list' => 20,
                'allow_early_registration' => true,
                'auto_seat_assignment' => true,
                'enable_qr_checkin' => true,
                'status' => 'registration_open',
                'is_featured' => true,
                'is_published' => true,
                'contact_name' => 'Tournament Director',
                'contact_email' => 'tournaments@tbilisipoker.ge',
                'contact_phone' => '+995 555 123 456',
            ],
            [
                'name' => 'Sunday Turbo Bounty',
                'slug' => 'sunday-turbo-bounty',
                'description' => 'Fast-paced turbo tournament with exciting bounties! Knock out players and collect bounties on your way to the top.',
                'start_date' => now()->addDays(10)->setTime(16, 0),
                'registration_start' => now(),
                'registration_end' => now()->addDays(10)->setTime(15, 45),
                'late_registration_minutes' => 30,
                'venue_name' => 'Tbilisi Poker Club',
                'address' => '12 Rustaveli Avenue',
                'city' => 'Tbilisi',
                'country' => 'Georgia',
                'postal_code' => '0108',
                'latitude' => 41.7151,
                'longitude' => 44.8271,
                'tournament_type' => 'bounty',
                'game_type' => 'texas_holdem',
                'structure' => 'nlhe',
                'total_tables' => 4,
                'seats_per_table' => 8,
                'buy_in' => 150.00,
                'entry_fee' => 15.00,
                'bounty_amount' => 50.00,
                'starting_stack' => 5000,
                'level_duration' => 10,
                'starting_blinds_small' => 25,
                'starting_blinds_big' => 50,
                'rebuys_allowed' => false,
                'addon_allowed' => false,
                'waiting_list_enabled' => true,
                'allow_early_registration' => true,
                'auto_seat_assignment' => true,
                'enable_qr_checkin' => true,
                'status' => 'registration_open',
                'is_featured' => true,
                'is_published' => true,
                'contact_email' => 'tournaments@tbilisipoker.ge',
                'contact_phone' => '+995 555 123 456',
            ],
            [
                'name' => 'Monthly Deep Stack Championship',
                'slug' => 'monthly-deep-stack-championship',
                'description' => 'Our biggest monthly event! Deep stacks, long levels, and a massive guaranteed prize pool. This is serious poker!',
                'start_date' => now()->addDays(20)->setTime(14, 0),
                'end_date' => now()->addDays(21)->setTime(4, 0),
                'registration_start' => now(),
                'registration_end' => now()->addDays(20)->setTime(13, 30),
                'late_registration_minutes' => 120,
                'venue_name' => 'Tbilisi Convention Center',
                'address' => '1 Freedom Square',
                'city' => 'Tbilisi',
                'country' => 'Georgia',
                'postal_code' => '0105',
                'latitude' => 41.6938,
                'longitude' => 44.8015,
                'tournament_type' => 'deep_stack',
                'game_type' => 'texas_holdem',
                'structure' => 'nlhe',
                'total_tables' => 10,
                'seats_per_table' => 9,
                'buy_in' => 500.00,
                'entry_fee' => 50.00,
                'guaranteed_prize' => 10000.00,
                'starting_stack' => 30000,
                'level_duration' => 40,
                'starting_blinds_small' => 25,
                'starting_blinds_big' => 50,
                'rebuys_allowed' => true,
                'rebuy_levels' => 6,
                'rebuy_cost' => 500.00,
                'addon_allowed' => true,
                'addon_cost' => 500.00,
                'addon_chips' => 30000,
                'waiting_list_enabled' => true,
                'max_waiting_list' => 30,
                'allow_early_registration' => true,
                'auto_seat_assignment' => true,
                'enable_qr_checkin' => true,
                'status' => 'published',
                'is_featured' => true,
                'is_published' => true,
                'contact_name' => 'Head Tournament Director',
                'contact_email' => 'big-events@tbilisipoker.ge',
                'contact_phone' => '+995 555 789 012',
            ],
            [
                'name' => 'Wednesday Freeroll',
                'slug' => 'wednesday-freeroll',
                'description' => 'Free entry tournament for all players! Win real prizes without any buy-in. Perfect for beginners and pros alike!',
                'start_date' => now()->addDays(5)->setTime(18, 0),
                'registration_start' => now(),
                'registration_end' => now()->addDays(5)->setTime(17, 45),
                'venue_name' => 'Tbilisi Poker Club',
                'address' => '12 Rustaveli Avenue',
                'city' => 'Tbilisi',
                'country' => 'Georgia',
                'postal_code' => '0108',
                'latitude' => 41.7151,
                'longitude' => 44.8271,
                'tournament_type' => 'freeroll',
                'game_type' => 'texas_holdem',
                'structure' => 'nlhe',
                'total_tables' => 3,
                'seats_per_table' => 9,
                'buy_in' => 0.00,
                'entry_fee' => 0.00,
                'guaranteed_prize' => 200.00,
                'starting_stack' => 3000,
                'level_duration' => 15,
                'starting_blinds_small' => 25,
                'starting_blinds_big' => 50,
                'rebuys_allowed' => false,
                'addon_allowed' => false,
                'waiting_list_enabled' => true,
                'max_waiting_list' => 10,
                'allow_early_registration' => true,
                'auto_seat_assignment' => true,
                'enable_qr_checkin' => true,
                'status' => 'registration_open',
                'is_featured' => false,
                'is_published' => true,
                'contact_email' => 'tournaments@tbilisipoker.ge',
            ],
            [
                'name' => 'Saturday PLO Championship',
                'slug' => 'saturday-plo-championship',
                'description' => 'For Pot-Limit Omaha enthusiasts! Test your skills in this exciting 4-card action-packed tournament.',
                'start_date' => now()->addDays(14)->setTime(15, 0),
                'registration_start' => now(),
                'registration_end' => now()->addDays(14)->setTime(14, 30),
                'late_registration_minutes' => 60,
                'venue_name' => 'Tbilisi Poker Club',
                'address' => '12 Rustaveli Avenue',
                'city' => 'Tbilisi',
                'country' => 'Georgia',
                'postal_code' => '0108',
                'latitude' => 41.7151,
                'longitude' => 44.8271,
                'tournament_type' => 'freezeout',
                'game_type' => 'plo',
                'structure' => 'pot_limit',
                'total_tables' => 5,
                'seats_per_table' => 6,
                'buy_in' => 200.00,
                'entry_fee' => 20.00,
                'guaranteed_prize' => 1500.00,
                'starting_stack' => 15000,
                'level_duration' => 25,
                'starting_blinds_small' => 25,
                'starting_blinds_big' => 50,
                'rebuys_allowed' => false,
                'addon_allowed' => false,
                'waiting_list_enabled' => true,
                'allow_early_registration' => true,
                'auto_seat_assignment' => true,
                'enable_qr_checkin' => true,
                'status' => 'published',
                'is_featured' => false,
                'is_published' => true,
                'contact_email' => 'tournaments@tbilisipoker.ge',
                'contact_phone' => '+995 555 123 456',
            ],
            // New tournaments (only seed these 2)
            [
                'name' => 'Monday Night Rebuy Madness',
                'slug' => 'monday-night-rebuy-madness',
                'description' => 'Fast-paced rebuy tournament with multiple rebuy opportunities! Action-packed Monday night poker with extended rebuy period.',
                'start_date' => now()->addDays(2)->setTime(20, 0),
                'end_date' => now()->addDays(3)->setTime(1, 0),
                'registration_start' => now(),
                'registration_end' => now()->addDays(2)->setTime(19, 30),
                'late_registration_minutes' => 45,
                'venue_name' => 'Batumi Casino & Poker Room',
                'address' => '25 Rustaveli Street',
                'city' => 'Batumi',
                'country' => 'Georgia',
                'postal_code' => '6010',
                'latitude' => 41.6168,
                'longitude' => 41.6367,
                'tournament_type' => 'rebuy',
                'game_type' => 'texas_holdem',
                'structure' => 'nlhe',
                'total_tables' => 8,
                'seats_per_table' => 9,
                'buy_in' => 75.00,
                'entry_fee' => 7.50,
                'guaranteed_prize' => 2500.00,
                'starting_stack' => 8000,
                'level_duration' => 15,
                'starting_blinds_small' => 25,
                'starting_blinds_big' => 50,
                'rebuys_allowed' => true,
                'rebuy_levels' => 8,
                'rebuy_cost' => 75.00,
                'addon_allowed' => true,
                'addon_cost' => 75.00,
                'addon_chips' => 8000,
                'waiting_list_enabled' => true,
                'max_waiting_list' => 25,
                'allow_early_registration' => true,
                'require_approval' => false,
                'auto_seat_assignment' => true,
                'enable_qr_checkin' => true,
                'status' => 'registration_open',
                'is_featured' => true,
                'is_published' => true,
                'contact_name' => 'Batumi Tournament Manager',
                'contact_email' => 'batumi@tbilisipoker.ge',
                'contact_phone' => '+995 555 234 567',
            ],
            [
                'name' => 'Thursday Progressive Bounty Knockout',
                'slug' => 'thursday-progressive-bounty-knockout',
                'description' => 'Progressive bounty tournament where bounties increase with each knockout! The longer you survive, the more valuable your bounty becomes.',
                'start_date' => now()->addDays(4)->setTime(19, 30),
                'end_date' => now()->addDays(5)->setTime(0, 30),
                'registration_start' => now(),
                'registration_end' => now()->addDays(4)->setTime(19, 0),
                'late_registration_minutes' => 30,
                'venue_name' => 'Kutaisi Poker House',
                'address' => '8 Agmashenebeli Avenue',
                'city' => 'Kutaisi',
                'country' => 'Georgia',
                'postal_code' => '4600',
                'latitude' => 42.2679,
                'longitude' => 42.7016,
                'tournament_type' => 'bounty',
                'game_type' => 'texas_holdem',
                'structure' => 'nlhe',
                'total_tables' => 7,
                'seats_per_table' => 8,
                'buy_in' => 120.00,
                'entry_fee' => 12.00,
                'bounty_amount' => 40.00,
                'progressive_bounty' => true,
                'starting_stack' => 12000,
                'level_duration' => 18,
                'starting_blinds_small' => 25,
                'starting_blinds_big' => 50,
                'rebuys_allowed' => false,
                'addon_allowed' => false,
                'waiting_list_enabled' => true,
                'max_waiting_list' => 15,
                'allow_early_registration' => false,
                'require_approval' => true,
                'auto_seat_assignment' => false,
                'enable_qr_checkin' => false,
                'status' => 'published',
                'is_featured' => false,
                'is_published' => true,
                'contact_name' => 'Kutaisi Tournament Director',
                'contact_email' => 'kutaisi@tbilisipoker.ge',
                'contact_phone' => '+995 555 345 678',
            ],
        ];

        // Only seed the last 2 new tournaments
        $newTournaments = array_slice($tournaments, -2);
        foreach ($newTournaments as $tournamentData) {
            Tournament::updateOrCreate(
                ['slug' => $tournamentData['slug']],
                $tournamentData
            );
        }
    }
}
